version: '3.8'

services:
  order-receiver:
    build:
      context: .
      dockerfile: DockerfileReceiver
    ports:
      - "3000:3000"
    networks:
      - quickfix

  order-generator:
    build:
      context: .
      dockerfile: DockerfileGenerator
    depends_on:
      - order-receiver
    networks:
      - quickfix

networks:
  quickfix: